PackageIdentifier: Melodex.Melodex
PackageVersion: 0.7.2
InstallerType: inno
Scope: machine

Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Cliff-Lee/melodex/releases/download/v0.7.2/Melodex-Windows-x64-Setup.exe
    InstallerSha256: D4AE4FDE8E294EB58EF6741899B9DB5648B614F79B7B357B2774CEDE86E68B41

ManifestType: installer
ManifestVersion: 1.12.0
